# This file defines the options for the manual alarm control panel

- platform: manual
  name: Home Alarm
  delay_time: 30 # TODO: Find an optimal value here
  arming_time: 30 # TODO: Find an optimal value here
  trigger_time: 30 # TODO: Find an optimal value here
  armed_home:
    arming_time: 0