# There's a lot here that I need to get rid of/move somewhere else 
# from my old configuration.yaml. This file will ecentually be deleted.

ffmpeg:

logger:
  default: info

group: ~

tts:
  - platform: google_translate

recorder:
  db_url: !secret mysql_connection_string

notify:
  - platform: group
    name: everyone_ios
    services:
      - service: mobile_app_austins_iphone
      - service: mobile_app_rachaels_iphone
  - name: RG Discord Server
    platform: rest
    method: POST
    message_param_name: content
    resource: !secret rg_server_webhook

binary_sensor:
  - platform: ffmpeg_noise
    input: rtsp://10.0.1.38/img/audio.sav
    initial_state: false
    duration: 2
    peak: -32