- id: '1589767890705'
  alias: AC Leak Notification
  description: Notify Austin and Rachael when a leak is detected
  trigger:
  - entity_id: sensor.ac_leak_detector
    platform: state
    to: '255'
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
      message: A leak has been detected near the air conditioner!
      title: Leak Detected
    service: notify.mobile_app_austins_iphone
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
      message: A leak has been detected near the air conditioner!
      title: Leak Detected
    service: notify.mobile_app_rachaels_iphone
- id: '1590463525502'
  alias: Anti-Snooze
  description: ''
  trigger:
  - platform: webhook
    webhook_id: antisnooze
  condition:
  - condition: template
    value_template: '{{ now().date() > strptime(states(''input_datetime.last_snooze_date''),
      ''%Y-%m-%d'').date() }}'
  action:
  - data_template:
      date: '{{ now().date() }}'
    entity_id: input_datetime.last_snooze_date
    service: input_datetime.set_datetime
  - data: {}
    service: script.1590461886795
- id: '1591589835737'
  alias: Light up the nursery
  description: ''
  trigger:
  - device_id: 24a7a9e76b1a422cbdd8513900fd191b
    domain: binary_sensor
    entity_id: binary_sensor.nursery_motion
    platform: device
    type: motion
  condition:
  - below: '100'
    condition: numeric_state
    entity_id: sensor.nursery_illuminance
  action:
  - brightness_pct: 10
    device_id: a6e3823a3ba841efa71097c6935c9110
    domain: light
    entity_id: light.rocker_lamp
    type: turn_on
- id: '1591589982645'
  alias: Turn off nursery lights
  description: ''
  trigger:
  - device_id: 24a7a9e76b1a422cbdd8513900fd191b
    domain: binary_sensor
    entity_id: binary_sensor.nursery_motion
    for:
      hours: 0
      minutes: 15
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: a6e3823a3ba841efa71097c6935c9110
    domain: light
    entity_id: light.28167_zw3104_plug_in_smart_dimmer_single_plug_level
    type: turn_off
- id: '1591979902035'
  alias: Don’t forget the baby!
  description: ''
  trigger:
  - entity_id: sensor.austins_iphone_activity
    from: Automotive
    platform: state
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
      message: Don't forget the baby!
    service: notify.mobile_app_austins_iphone
- id: '1592459342650'
  alias: Austin Bedside Button
  description: ''
  trigger:
  - entity_id: sensor.austin_bedside_button_click
    platform: state
    to: single
  condition: []
  action:
  - device_id: 9e37e275c7ea47e391c393070ff9c17c
    domain: light
    entity_id: light.austin_bedside
    type: toggle
- id: '1592459512451'
  alias: Rachael Button
  description: ''
  trigger:
  - entity_id: sensor.rachael_bedside_button_click
    platform: state
    to: single
  condition: []
  action:
  - device_id: 6d76bee1732c48f083abddcf746bffd2
    domain: light
    entity_id: light.rachael_bedside
    type: toggle
