- id: '1589767890705'
  alias: AC Leak Notification
  description: Notify Austin and Rachael when a leak is detected
  trigger:
  - entity_id: sensor.ac_leak_detector
    platform: state
    to: '255'
  condition: []
  action:
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
      message: A leak has been detected near the air conditioner!
      title: Leak Detected
    service: notify.mobile_app_austins_iphone
  - data:
      data:
        push:
          sound:
            critical: 1
            name: default
      message: A leak has been detected near the air conditioner!
      title: Leak Detected
    service: notify.mobile_app_rachaels_iphone
- id: '1589774515252'
  alias: Therapy Notification
  description: Notify Rachael when Austin arrives at Therapy
  trigger:
  - entity_id: person.austin_rainwater
    event: enter
    platform: zone
    zone: zone.therapy
  condition: []
  action:
  - data:
      message: Austin has arrived at therapy
      title: Location Update
    service: notify.mobile_app_rachaels_iphone
- id: '1589774699215'
  alias: Therapy -> Home Notification
  description: Notify Rachael when Austin leaves therapy
  trigger:
  - entity_id: person.austin_rainwater
    event: leave
    platform: zone
    zone: zone.therapy
  condition: []
  action:
  - data:
      message: Austin has left therapy
      title: Location Update
    service: notify.mobile_app_rachaels_iphone
