default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  external_url: https://home.heckin.io
  internal_url: http://10.0.1.2:8123

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate

camera:
 - platform: aarlo

# Integrations

konnected: !include integrations/konnected.yaml
homekit: !include integrations/homekit.yaml
aarlo: !include integrations/aarlo.yaml