default_config:

logger:
  default: info

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

tts:
  - platform: google_translate

camera:
 - platform: aarlo

notify:
  - platform: group
    name: everyone_ios
    services:
      - service: mobile_app_austins_iphone
      - service: mobile_app_rachaels_iphone
   

# Integrations

konnected: !include integrations/konnected.yaml
homekit: !include integrations/homekit.yaml
aarlo: !include integrations/aarlo.yaml