default_config:

logger:
  default: info

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
timer: !include timer.yaml

tts:
  - platform: google_translate

camera:
 - platform: aarlo

recorder:
  db_url: !secret mysql_connection_string

notify:
  - platform: group
    name: everyone_ios
    services:
      - service: mobile_app_austins_iphone
      - service: mobile_app_rachaels_iphone
   

# Integrations

konnected: !include integrations/konnected.yaml
aarlo: !include integrations/aarlo.yaml
