default_config:
ffmpeg:

logger:
  default: info

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
timer: !include timer.yaml
camera: !include camera.yaml

tts:
  - platform: google_translate

recorder:
  db_url: !secret mysql_connection_string

notify:
  - platform: group
    name: everyone_ios
    services:
      - service: mobile_app_austins_iphone
      - service: mobile_app_rachaels_iphone
  - name: RG Discord Server
    platform: rest
    method: POST
    message_param_name: content
    resource: !secret rg_server_webhook
   

# Integrations

konnected: !include integrations/konnected.yaml
aarlo: !include integrations/aarlo.yaml

binary_sensor:
  - platform: ffmpeg_noise
    input: rtsp://10.0.1.38/img/audio.sav
    initial_state: false
    duration: 2
    peak: -32

input_boolean:
  babymonitor:
    name: Baby Monitor
    initial: off