# Override the default config because I'm tired of seeing Home Assistant Cloud
config: 
frontend:
  themes: !include_dir_merge_named themes
history:
input_boolean: !include input/boolean.yaml
input_datetime: !include input/datetime.yaml
input_number: !include input/number.yaml
input_select: !include input/select.yaml
input_text: !include input/text.yaml
logbook:
map:
mobile_app:
person:
ssdp: 
sun:
system_health:
updater:
zeroconf:
zone:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://home.heckin.io

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
