- platform: apcupsd
  scan_interval: 5
  resources:
    - starttime
    - status
    - linev
    - loadpct
    - bcharge
    - timeleft
    - mbattchg
    - mintimel
    - maxtime
    - sense
    - lotrans
    - hitrans
    - alarmdel
    - battv
    - lastxfer
    - numxfers
    - tonbatt
    - cumonbatt
    - xoffbatt
    - selftest
    - statflag
    - battdate
    - nominv
    - nombattv
    - nompower