- platform: template
  sensors:
    bedroom_temperature:
      friendly_name: Average Bedroom Temperature
      unit_of_measurement: °F
      entity_id:
        - group.bedroom_temperature
      device_class: temperature
      value_template: >-
        {# Get all of the temperature values and average them #}
        {%- set values = expand('group.bedroom_temperature')
            | rejectattr('state', 'equalto', 'unknown')
            | rejectattr('state', 'equalto', 'unavailable')
            | map(attribute='state')
            | map('int')
            | list
        -%}
        {{ values | sum / values | count }}