- platform: template
  sensors:
    bedroom_temperature:
      friendly_name: Average Bedroom Temperature
      unit_of_measurement: °F
      entity_id:
        - sensor.austin_bedside_button_temperature
        - sensor.rachael_bedside_button_temperature
        - sensor.bedroom_motion_temperature
        - sensor.bedroom_door_temperature
      device_class: temperature
      value_template: >-
        {# Get all of the temperature values and average them #}
        {%- set values = expand('group.bedroom_temperature')
            | rejectattr('state', 'equalto', 'unknown')
            | rejectattr('state', 'equalto', 'unavailable')
            | map(attribute='state')
            | map('float')
            | list
        -%}
        {{ values | sum / values | count }}
      attribute_templates:
        minimum_temperature: >-
          {{ expand('group.bedroom_temperature')
            | rejectattr('state', 'equalto', 'unknown')
            | rejectattr('state', 'equalto', 'unavailable')
            | map(attribute='state')
            | map('float')
            | min }}
        maximum_temperature: >-
          {{ expand('group.bedroom_temperature')
            | rejectattr('state', 'equalto', 'unknown')
            | rejectattr('state', 'equalto', 'unavailable')
            | map(attribute='state')
            | map('float')
            | max }}
        included_entities: >-
          {{ expand('group.bedroom_temperature')
            | rejectattr('state', 'equalto', 'unknown')
            | rejectattr('state', 'equalto', 'unavailable')
            | list
            | count
          }}
        # TODO: Missing entity count, etc