# These lights just connect to the automations; they actually don't do anything with Tasmota

- platform: mqtt
  schema: json
  name: Left Cloud
  unique_id: left_cloud
  command_topic: tasmotabridge/leftcloud/set
  state_topic: tasmotabridge/leftcloud/state
  brightness: true
  brightness_scale: 100
  rgb: true
  color_temp: true
  min_mireds: 153
  max_mireds: 500
  retain: true

- platform: mqtt
  schema: json
  name: Right Cloud
  unique_id: right_cloud
  command_topic: tasmotabridge/rightcloud/set
  state_topic: tasmotabridge/rightcloud/state
  brightness: true
  brightness_scale: 100
  rgb: true
  color_temp: true
  min_mireds: 153
  max_mireds: 500
  retain: true

- platform: mqtt
  schema: json
  name: Cloud Lamps
  unique_id: cloud_group
  command_topic: tasmotabridge/clouds/set
  # Command only--there is no state topic
  brightness: true
  brightness_scale: 100
  rgb: true
  color_temp: true
  min_mireds: 153
  max_mireds: 500
