# These lights just connect to the automations; they actually don't do anything with Tasmota

- platform: mqtt
  schema: json
  name: Left Cloud
  unique_id: left_cloud
  command_topic: tasmotabridge/leftcloud/set
  state_topic: tasmotabridge/leftcloud/state
  brightness: true
  brightness_scale: 100
  white_value: true
  rgb: true
  retain: true
  optimistic: true # TODO: Remove. I'm just figuring it out right now.

